In [ ]:
Archana Singh
24-27-10
Mtech Data Science
Assignment 2

In [5]:
# 1 question

#a)
import numpy as np
var1=np.arange(31)
print("output of (a)")
print("var1\n",var1)
print("shape of var1",np.shape(var1))

#b)
var1=np.delete(var1,30)
var2=var1.reshape(3,10)
print()
print("output of (b)")
print("var2\n",var2)
print("Shape of var2 ",np.shape(var2))

#c)
var3=var1.reshape(2,3,5)
print()
print("output of (c)")
print("var3\n",var3)
print("shape of var3 ",np.shape(var3))
print()

#d)
print("output of (d)")
var2[1,0]=-1
print("matrix after change value of variable \n")
print("var2\n",var2)
print()
print("var1\n",var1)
print()
print("var3\n",var3)
print()
#reshape return the view of the variable(array) which means any change in original array(variable) 
#will affect the view of the variable(array) and vice versa

#e)
print("output of (e)")
sum_secdim = np.sum(var3, axis=1)
print("Sum var3 over its second dimension")
print(sum_secdim)
sum_tdim = np.sum(var3, axis=2)
print("\nSum var3 over its third dimension")
print(sum_tdim)
print("\nSum var3 over both its first and third dimensions")
sum_fistdim = np.sum(var3, axis=(0, 2))
print(sum_fistdim)
print()
# f)
print("\noutput of (f)")
print("(i) second row of var2 \n",var2[1,])
print("\n(ii) last column of var2 \n",var2[0:3,-1])
print("\n(iii) top right 2X2 submatrix of var2\n", var2[0:2,-2:])

output of (a)
var1
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30]
shape of var1 (31,)

output of (b)
var2
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Shape of var2  (3, 10)

output of (c)
var3
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
shape of var3  (2, 3, 5)

output of (d)
matrix after change value of variable 

var2
 [[ 0  1  2  3  4  5  6  7  8  9]
 [-1 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]

var1
 [ 0  1  2  3  4  5  6  7  8  9 -1 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

var3
 [[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [-1 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]

output of (e)
Sum var3 over its second dimension
[[ 4 18 21 24 27]
 [60 63 66 69 72]]

Sum var3 over its third dimension
[[ 10  35  49]
 [ 85 110 135]]

Sum var3 over bo

In [90]:
#2 Question
#a)
vector=np.arange(10)
#print(vector)
ve=vector+1
print("output of (a)")
print("vector",ve)
print()
#b)
t=vector[:, np.newaxis]
print("output of (b)")
print(t+vector)
print()
#c)
print("output of (c)")
import numpy.random as npr
data = np.exp(npr.randn ( 50 , 5))
#print(data)
u=np.mean(data,axis=0)
v=np.std(data,axis=0)
print("mean of data:",u)
print("standard variance of data:",v)
s=data-u
normalized=s/v
print("\nStandarized Data ")
#print(normalized)
print("mean of standardize form:",np.round(np.mean(normalized,axis=0)))
print("variance of standardize form:",np.round(np.var(normalized,axis=0)))
print()




output of (a)
vector [ 1  2  3  4  5  6  7  8  9 10]

output of (b)
[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]]

output of (c)
mean of data: [1.34770537 1.90339864 1.35887604 1.56437937 1.87701088]
standard variance of data: [1.06133655 2.65839188 1.31783155 1.58250601 2.60874916]

Standarized Data 
mean of standardize form: [-0. -0.  0.  0. -0.]
variance of standardize form: [1. 1. 1. 1. 1.]



In [88]:
# 3 Question
# a)
N=12
import numpy.linalg
def vandermonde (N):
  vec = np.arange (N) +1
  x=vec[:,np.newaxis]
  #print("column Vector :\n",x)
  p=np.arange(N)
  vand=x**p
  #print("Vandermonde matrix :\n",vander)
  return vand  
print("Output of (a)\n")    
vander=vandermonde(N)
print("Vandermonde matrix :\n",vander)
print()

#b)
print("output of (b)\n")
x1=np.ones(N)
x=x1[:,np.newaxis]
#print(x)
b=np.dot(vander,x)
print("vector b \n",b)
print()

#c)
# as we know vender*x=b then x=(vender)*(-1)*b
print("output of (c)")
print()
vander=vandermonde(N)
inv_ven=np.linalg.inv(vander)
req_x=np.dot(inv_ven,b)
print("X by using inverse of matrix \n",req_x)
print()

'''By using naive way we have to perform two operation (invert and multiply), When you invert the matrix and then multiply by b matrix, 
you're performing more floating-point operations, each with some roundoff error. These errors can accumulate,
that's why we are not getting accurate x matrix '''


#d)
print("Output of (d)")
req_x=np.linalg.solve(vander, b)
print("X by using Solve \n",x)

#where as solve() method use more stable algorithm to solve the linear system so,it is more accurate 
 #    this method is more consider when the matrix is singular or close to singular 



Output of (a)

Vandermonde matrix :
 [[          1           1           1           1           1           1
            1           1           1           1           1           1]
 [          1           2           4           8          16          32
           64         128         256         512        1024        2048]
 [          1           3           9          27          81         243
          729        2187        6561       19683       59049      177147]
 [          1           4          16          64         256        1024
         4096       16384       65536      262144     1048576     4194304]
 [          1           5          25         125         625        3125
        15625       78125      390625     1953125     9765625    48828125]
 [          1           6          36         216        1296        7776
        46656      279936     1679616    10077696    60466176   362797056]
 [          1           7          49         343        2401       1